gender = factor(c('M','F','F','M','F'))
height = c(161,162,163,164,165)
first=c('abcd','xyzw','lnop','qwer',"poiu")
last = c('abc','xyz','lno','qwe','poi')
ppl = data.frame(gender,height,first,last)
print(ppl)
